services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: innerbright-frontend
    container_name: innerbright-frontend
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
    restart: always
